Http poll wtf
RealConrad/42webserv pull request #23
Opened 2024-04-12 17:03 UTC by kglebows

## 1. poll() fix
POLLIN and POLLOUT working correctly now.
Connections are not being closed by server timeout YET.

## 2. signal catcher
So we kill the process gracefully 

## 3. HTTP header response fix
Who could have guessed that the message needs a length? 🤔 
Also, keep-alive needs to be stored somewhere along with maybe more socket-info for formulating HTTP responses. 

## 4. poll() errno and log update
added errno, changed some INFO logs to include important variables.
Do not remove commented-out DEBUG requests and responses!
i will use it for further testing and development 

## 5. added flavicon
Look how magnificent!
type for header response needs to be adjusted tho...

2024-04-12 18:41 UTC, RealConrad requested changes

2024-04-12 18:41 UTC, RealConrad commented on src/HTTPResponse.cpp
> +std::string intToString(size_t value) { //TODO move to utils
Move this into `Utils.cpp` now. No point in doing this in another PR.

2024-04-12 18:41 UTC, RealConrad commented on src/SocketManager.cpp
> +			// && this->clientStates[this->fds[i].fd].responseComplete == false) { // Ready for writing
Remove comment

2024-04-12 18:41 UTC, RealConrad commented on src/SocketManager.cpp
> +					handleClientRequest(i);
Rather pass down the entire struct like so:
```cpp
handleClient(this->fds[i]);
```
As you are literally doing this inside the function lol:
```cpp
int fd = this->fds[i];
```

2024-04-12 18:41 UTC, RealConrad commented on src/SocketManager.cpp
> +void SocketManager::handleClientRequest(int i) {
Change this to take the entire fd struct, not just `i`

2024-04-12 18:41 UTC, RealConrad commented on src/SocketManager.cpp
> +	int fd = this->fds[i].fd;
Change this. mentioned in above comments

2024-04-12 18:41 UTC, RealConrad commented on src/SocketManager.cpp
> +            SUCCESS("Succe ssfully read client request");
?

2024-04-12 18:41 UTC, RealConrad commented on includes/SocketManager.hpp
> +		void handleClientRequest(int i);
Pass down the entire `fd struct`, not `i`

2024-04-12 18:41 UTC, RealConrad commented on includes/SocketManager.hpp
> +		void sendResponse(int i);
Pass down the entire `fd struct`, not `i`

2024-04-12 18:41 UTC, RealConrad commented on src/SocketManager.cpp
> +	DEBUG(std::endl << buffer << std::endl);
Remove debug log. Should not be needed in the `main` branch.

2024-04-12 18:41 UTC, RealConrad commented on src/SocketManager.cpp
> +				sendResponse(i);
Pass down entire `this->fds[i]` not just `i`

2024-04-12 18:41 UTC, RealConrad commented on src/SocketManager.cpp
> +    	// sendResponse(fd);
Remove commented out code

2024-04-12 18:41 UTC, RealConrad commented on src/SocketManager.cpp
> +void SocketManager::sendResponse(int i) {
Pass down entire `this->fd[i]` struct, not just `i`

2024-04-12 18:41 UTC, RealConrad commented on src/SocketManager.cpp
> +	int fd = this->fds[i].fd;
Remove this and use the pass down value instead. No need to create a local variable for this

2024-04-12 18:41 UTC, RealConrad commented on src/SocketManager.cpp
> +		usleep(10000);
Why we do have a usleep here?

2024-04-12 18:41 UTC, RealConrad commented on src/SocketManager.cpp
> +            // closeConnection(fd);
Remove commented out code

2024-04-12 18:41 UTC, RealConrad commented on src/SocketManager.cpp
> +            // clientStates[fd].responseComplete = true;
Remove commented out code

2024-04-12 18:41 UTC, RealConrad commented on includes/SocketManager.hpp
> +		void processRequest(int fd);
Pass down entire `fds struct`, not `i`

2024-04-12 18:41 UTC, RealConrad commented on src/utils/utils.cpp
> +	*exit_code = value;
Remove these functions. they are not used anymore

2024-04-12 18:41 UTC, RealConrad commented on includes/Utils.hpp
> +
Remove this. They are not used anymore

2024-04-12 18:41 UTC, RealConrad commented on src/SocketManager.cpp
> +			// 	DEBUG("*");
Remove commented out code

2024-04-12 18:41 UTC, RealConrad commented on src/main.cpp
> +#include "Utils.hpp"
Remove `<signal.h>` and `"Utils.hpp"` From what i see, they are not needed

2024-04-12 18:41 UTC, RealConrad commented on src/main.cpp
> +
Remove new line

2024-04-13 11:00 UTC, kglebows commented
Added review fix and fixed fcntl

2024-04-13 11:04 UTC, RealConrad approved these changes

2024-04-13 11:04 UTC, merged