Directory Listing
RealConrad/42webserv pull request #30
Opened 2024-04-14 12:07 UTC by kglebows

2024-04-15 15:26 UTC, RealConrad requested changes

2024-04-15 15:26 UTC, RealConrad commented on src/HTTPResponse.cpp
> +			if (dir != nullptr) {
this is c++11

2024-04-15 15:26 UTC, RealConrad commented on src/HTTPResponse.cpp
> +				while ((entry = readdir(dir)) != nullptr) {
c++11 keyword

2024-04-15 15:26 UTC, RealConrad commented on src/HTTPResponse.cpp
> +					if (strcmp(entry->d_name, ".") == 0)
Dont use C-style funtions, use cpp

2024-04-15 15:26 UTC, RealConrad commented on src/HTTPResponse.cpp
> +	if (uri.back() == '/') {
`.back()` is c++11

2024-04-15 17:34 UTC, RealConrad requested changes

2024-04-15 17:34 UTC, RealConrad commented on src/SocketManager.cpp
> +#include "signal.h"
Can you move this into the `.hpp` file? As thats where all of our other library includes are

2024-04-15 17:34 UTC, RealConrad commented on src/HTTPResponse.cpp
> +	std::string fullPath = serverConfig.rootDirectory + uri;
Can you break up this function into helper functions? The function is around 70 lines of code and is hard to read

2024-04-16 07:18 UTC, kglebows commented
Splitted function and added multiple slashes handler:
<img width="542" alt="image" src="https://github.com/RealConrad/42webserv/assets/131430279/2c733b2d-f0d3-4d69-817f-3c495a30fcb7">

2024-04-16 08:07 UTC, RealConrad approved these changes

2024-04-16 08:07 UTC, merged